name: Générer les index.json

on:
  push:
    branches:
      - main
    paths:
      - 'dossiers/**/contenu/*.md'

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v4

      - name: Exécuter le script
        run: python script.py

      - name: Créer ou mettre à jour la PR
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "auto: mise à jour des index.json"
          branch: auto/update-index
          title: "auto: mise à jour des index.json"
          body: "Mise à jour automatique des index.json suite à un ajout ou suppression de document."
          base: main